name: Dockerize and Push

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    outputs:
      image_tag:
        description: "Docker image tag"
        value: ${{ jobs.dockerize.outputs.image_tag }}

jobs:
  dockerize:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Image Tag
        id: set-tag
        run: echo "image_tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build & Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.set-tag.outputs.image_tag }}
        run: |
          docker build -t $ECR_REGISTRY/${{ inputs.image_name }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ inputs.image_name }}:$IMAGE_TAG
